### ISSUE TITLE
Not working on micro 2.0.2

### ISSUE THREAD

**Issue by rochacbruno** [tommyshem/micro-rust-plugin#1]
I have 

```
❯ micro -version    
Version: 2.0.2
Commit hash: c51f849
Compiled on February 26, 2020

```

and now looks like the folder for plugins is called `plug`

```
# Plugins

Micro supports creating plugins with a simple Lua system. Plugins are
folders containing Lua files and possibly other source files placed
in `~/.config/micro/plug`. The plugin directory (within `plug`) should
contain at least one Lua file and an `info.json` file. The info file
provides additional information such as the name of the plugin, the
plugin's website, dependencies, etc... Here is an example info file
from the go plugin, which has the following file structure:

```
~/.config/micro/plug/go-plugin/
    go.lua
    repo.json
    help/
        go-plugin.md
```

The `go.lua` file contains the main code for the plugin, though the
code may be distributed across multiple Lua files. The `info.json`
file contains information about the plugin such as the website,
description, version, and any requirements. Plugins may also
have additional files which can be added to micro's runtime files,
of which there are 5 types:

* Colorschemes
* Syntax files
* Help files
* Plugin files
* Syntax header files

In most cases, a plugin will want to add help files, but in certain
cases a plugin may also want to add colorschemes or syntax files. It
is unlikely for a plugin to need to add plugin files at runtime or
syntax header files. No directory structure is enforced but keeping
runtime files in their own directories is good practice.
```

The install methos showed here on readme is not working.

**Comment by tommyshem** [comment]
I have started converting the rust plugin to Micro editor version 2 as the api for the  plugins has changed.

You can try branch micro-v2 the instructions are on the README.md main branch for installing version 2 micro rust plugin.

There might still be problems with it as only just started converting but you can check it out from time to time and test it, if you like or just wait until I have finished converting.

I will post another comment here when I have finished converting it fully.

**Comment by tommyshem** [comment]
You can try it now. Let me know if something does not work.

Instructions are on the README.md file.

**Comment by rochacbruno** [comment]
thanks that is working! awesome work! thanks.

I will try ot make it work with `cargo play` https://github.com/fanzeyi/cargo-play/pull/21
